{% set name = "django_param" %}
{% set version = "0.0.8" %}
{% set sha256 = "a953c15de7ea5998f225fa369cd8bbe963a9f4d338b1f51241d418b726b6104c" %}
{% set os_distribution = "linux-x86_64" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ os_distribution }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - django == 2.2.6
    - pyyaml == 5.1.2
    - django-gravatar2 == 1.4.2
    - psycopg2 == 2.8.4
    - param == 1.9.3
    - django-select2 == 7.1.2
    - django-colorfield == 0.3.2

test:
  imports:
    - pytest
    - param
    - django_param.forms

about:
  home: https://github.com/Aquaveo/django_param
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Prefer the short version, e.g: GPL-2.0 instead of GNU General Public License version 2.0
  # See https://opensource.org/licenses/alphabetical
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'django_param provides ParamForm class which allows python param to be used in django form.'

  # The remaining entries in this section are optional, but recommended.
  description: django_param provides ParamForm class which allows python param to be used in django form.
  doc_url: https://github.com/Aquaveo/django_param/blob/master/README.rst
  dev_url: https://github.com/Aquaveo/django_param

extra:
  recipe-maintainers:
    - swainn
    - htran84
    - gagelarsen
